##### Hooks #####
set-hook -g session-created "set -p allow-passthrough on"
set-hook -g pane-died "set -p allow-passthrough on"
set-option -g focus-events on

##### Prefix #####
set-option -g prefix C-a
unbind C-b
bind C-a send-prefix

##### Status Bar #####
set -g status-position top
set -g status-left ""
set -g status-right "#S "

##### Mouse Mode #####
set -g mouse on

##### Indexing #####
set -g base-index 1

##### Window Shortcuts #####
bind -n C-j select-window -t :1
bind -n C-k select-window -t :2
bind -n C-u select-window -t :3
#bind -n C-q kill-window

##### Terminal Colors #####
set -g default-terminal "tmux-256color"
set -as terminal-overrides ',*:RGB'

##### Catppuccin Theme #####
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_window_status_style "basic"
set -g @catppuccin_window_number_position "left"
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# Use tmux scrollback with mouse wheel
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" \
  "send-keys -M" "copy-mode -e; send-keys -M"

bind -n WheelDownPane send-keys -M

# Vi mode (recommended)
setw -g mode-keys vi

# Drag select in copy mode
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "wl-copy"
